"use client";

import type { InstalledCustomApp } from "./custom-app-types";
import type { CustomAppMarketItem, CustomAppPackageKind } from "./custom-app-market-types";
import { getCustomAppPrimaryTags } from "./custom-app-storage";

type MarketListResponse = { ok: boolean; apps?: CustomAppMarketItem[]; app?: CustomAppMarketItem; id?: string; setupRequired?: boolean; error?: string };
type MarketAssetResponse = { ok: boolean; url?: string; path?: string; kind?: CustomAppPackageKind; size?: number; error?: string };
export type CustomAppMarketAdminView = "pending" | "approved" | "rejected" | "all";
async function readJson<T>(response: Response): Promise<T> { const data = await response.json().catch(() => ({})); if (!response.ok || data?.ok === false) throw new Error(data?.error || `HTTP ${response.status}`); return data as T; }
async function fetchJson<T>(input: RequestInfo | URL, init?: RequestInit): Promise<T> { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 15000); try { const response = await fetch(input, { ...init, credentials: "include", signal: controller.signal }); return await readJson<T>(response); } catch (err) { if (err instanceof DOMException && err.name === "AbortError") throw new Error("请求超时，请检查网络连接。"); throw err; } finally { window.clearTimeout(timeout); } }
export async function fetchCustomAppMarketItems(): Promise<CustomAppMarketItem[]> { const data = await fetchJson<MarketListResponse>("/api/app-market/apps-lite"); return data.apps ?? []; }
export async function fetchCustomAppMarketItemByAppId(appId: string): Promise<CustomAppMarketItem | null> { const data = await fetchJson<MarketListResponse>(`/api/app-market/apps?appId=${encodeURIComponent(appId)}`, { cache: "no-store" }); return data.app ?? null; }
export async function fetchMyCustomAppMarketItems(): Promise<CustomAppMarketItem[]> { const data = await fetchJson<MarketListResponse>("/api/app-market/apps-lite?mine=1", { cache: "no-store" }); return data.apps ?? []; }
export async function fetchCustomAppMarketAdminItems(input: { adminKey: string; view: CustomAppMarketAdminView }): Promise<CustomAppMarketItem[]> { const view = encodeURIComponent(input.view); const data = await fetchJson<MarketListResponse>(`/api/app-market/apps?admin=1&view=${view}`, { cache: "no-store", headers: { "x-app-market-admin-key": input.adminKey } }); return data.apps ?? []; }
export async function uploadCustomAppPackageAsset(input: { file: File; filename: string }): Promise<{ url: string; path: string; kind: CustomAppPackageKind; size: number }> { const formData = new FormData(); formData.append("file", input.file, input.filename); const data = await fetchJson<MarketAssetResponse>("/api/app-market/assets", { method: "POST", body: formData }); if (!data.url || !data.path || !data.kind) throw new Error(data.error || "应用包上传失败"); return { url: data.url, path: data.path, kind: data.kind, size: Number(data.size ?? input.file.size) }; }
const ICON_SAFE_LENGTH = 160_000; const ICON_HARD_LIMIT = 280_000;
async function compressIconForMarket(dataUrl?: string): Promise<string> { const icon = (dataUrl || "").trim(); if (!icon.startsWith("data:image/")) return ""; if (icon.length <= ICON_SAFE_LENGTH) return icon; if (typeof document === "undefined") return ""; try { const image = await new Promise<HTMLImageElement>((resolve, reject) => { const img = new Image(); img.onload = () => resolve(img); img.onerror = () => reject(new Error("图标解码失败")); img.src = icon; }); for (const size of [256, 128]) { const scale = Math.min(1, size / Math.max(image.naturalWidth || size, image.naturalHeight || size, 1)); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round((image.naturalWidth || size) * scale)); canvas.height = Math.max(1, Math.round((image.naturalHeight || size) * scale)); const ctx = canvas.getContext("2d"); if (!ctx) return ""; ctx.drawImage(image, 0, 0, canvas.width, canvas.height); const webp = canvas.toDataURL("image/webp", 0.85); if (webp.startsWith("data:image/webp") && webp.length <= ICON_HARD_LIMIT) return webp; const png = canvas.toDataURL("image/png"); if (png.length <= ICON_HARD_LIMIT) return png; } return ""; } catch { return ""; } }
export async function publishCustomAppMarketItem(input: { app: InstalledCustomApp; packageUrl: string; packagePath: string; packageKind: CustomAppPackageKind; packageSize: number; version?: string; changelog?: string }): Promise<CustomAppMarketItem> { const version = input.version?.trim() || input.app.version; const data = await fetchJson<MarketListResponse>("/api/app-market/apps", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: input.app.name, version, changelog: input.changelog, description: input.app.description, iconDataUrl: await compressIconForMarket(input.app.iconDataUrl), permissions: input.app.permissions, manifest: { ...input.app.manifest, version, primaryTags: getCustomAppPrimaryTags(input.app) }, packageUrl: input.packageUrl, packagePath: input.packagePath, packageKind: input.packageKind, packageSize: input.packageSize }) }); if (!data.app) throw new Error(data.error || "提交应用失败"); return data.app; }
export async function validateCustomAppMarketItem(input: { id?: string; app: InstalledCustomApp; version?: string }): Promise<void> { const version = input.version?.trim() || input.app.version; await fetchJson<MarketListResponse>("/api/app-market/apps", { method: input.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ validateOnly: true, id: input.id, name: input.app.name, version, description: input.app.description, iconDataUrl: input.app.iconDataUrl, permissions: input.app.permissions, manifest: { ...input.app.manifest, version, primaryTags: getCustomAppPrimaryTags(input.app) } }) }); }
export async function updateCustomAppMarketItem(input: { id: string; appId?: string; app?: InstalledCustomApp; name?: string; packageUrl?: string; packagePath?: string; packageKind?: CustomAppPackageKind; packageSize?: number; version?: string; description?: string; iconDataUrl?: string; changelog?: string }): Promise<CustomAppMarketItem> { const version = input.version?.trim() || input.app?.version; const rawIcon = input.iconDataUrl ?? input.app?.iconDataUrl; const data = await fetchJson<MarketListResponse>("/api/app-market/apps", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: input.id, appId: input.appId, name: input.name ?? input.app?.name, version, changelog: input.changelog, description: input.description ?? input.app?.description, iconDataUrl: rawIcon === undefined ? undefined : await compressIconForMarket(rawIcon), permissions: input.app?.permissions, manifest: input.app ? { ...input.app.manifest, version: version || input.app.version, primaryTags: getCustomAppPrimaryTags(input.app) } : undefined, packageUrl: input.packageUrl, packagePath: input.packagePath, packageKind: input.packageKind, packageSize: input.packageSize }) }); if (!data.app) throw new Error(data.error || "应用更新失败"); return data.app; }
export async function deleteCustomAppMarketItem(input: { id: string }): Promise<string> { const data = await fetchJson<MarketListResponse>("/api/app-market/apps", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); return data.app?.id || data.id || input.id; }
export async function recordCustomAppInstall(appId: string): Promise<void> { await fetchJson<MarketListResponse>("/api/app-market/apps", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: appId, action: "increment_install" }) }).catch(() => undefined); }
export async function reviewCustomAppMarketItem(input: { adminKey: string; id: string; action: "approve" | "reject" }): Promise<CustomAppMarketItem> { const data = await fetchJson<MarketListResponse>("/api/app-market/apps", { method: "PATCH", headers: { "Content-Type": "application/json", "x-app-market-admin-key": input.adminKey }, body: JSON.stringify({ id: input.id, action: input.action }) }); if (!data.app) throw new Error(data.error || "审核操作失败"); return data.app; }
